# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"

  errors:
    invalid_annotation_target: ignore
    # Treat missing returns as errors immediately
    body_might_complete_normally: error
    # Enforce const usage for performance
    prefer_const_constructors: warning

linter:
  rules:
    # Architecture & Performance
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print # Use logging_service instead
    - use_build_context_synchronously

    # Style & Readability
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
